### ISSUE TITLE
hi~灰常感谢你的多说组件，但是有个小问题

### ISSUE THREAD

**Issue by ellyliang** [xlsdg/vue-duoshuo#1]
![image](https://cloud.githubusercontent.com/assets/4658035/22020930/ac7126ce-dcf5-11e6-8272-12363120a017.png)
![image](https://cloud.githubusercontent.com/assets/4658035/22020962/d76e046e-dcf5-11e6-89d7-dcc9a7875553.png)

还有评论一个地方，其他地方也有评论了

**Comment by xlsdg** [comment]
非常感谢反馈，第一个error已经修复。第二个问题不太明白？能具体描述一下吗？

**Comment by ellyliang** [comment]
哈哈，忽略第二张图，不是问题。发现多说有个问题，从列表页跳到文章页，多说的评论框只能首次加载出来，第二次进去之后评论框就没出来了，不知道大神有没有遇到这个问题

**Comment by xlsdg** [comment]
第二次进去没出来，刚确认又是一个bug，已经修复，更新一下就好。

**Comment by ellyliang** [comment]
更新了代码之后，是出来了，但是还有个问题，评论内容没有了....只有刷新了之后才有，这是多说的bug?

**Comment by ellyliang** [comment]
![image](https://cloud.githubusercontent.com/assets/4658035/22140683/e7a4b6f4-df28-11e6-9827-a950bd26d70a.png)

**Comment by xlsdg** [comment]
我这边测试了一下，评论是可以出来的，检查一下 thread 的属性变量是不是发生了改变。

**Comment by ellyliang** [comment]
thread我传的是文章ID，
![image](https://cloud.githubusercontent.com/assets/4658035/22141465/29c183a6-df2d-11e6-8eaa-553b0b9f8c44.png)

如果写死一个的话是可以的，但是如果来回切换不同的文章，评论就会出不来

**Comment by xlsdg** [comment]
每一个thread对应的是每篇文章的id，这是对的。然后切换不同文章的时候，多说会去后台取对应文章id的评论数据，如果这篇文章没有人评论过，就是空白的，所以你的问题也就不存在了。你只要在每篇文章下面评论不同的内容，然后切换不同文章看看，就可以看到新评论了。

**Comment by ellyliang** [comment]
不是的呢，我每一篇文章都给对应的ID，然后也评论不一样的，但是切换不同的文章，看不到评论

**Comment by xlsdg** [comment]
有在线项目代码吗？这样子光说没法定问题

**Comment by ellyliang** [comment]
刚刚把我的业余项目部署上了，多说的组件问题可以看了，第一次进去是可以的，但是第二次进去评论就不见了。看了ID是传了的

**Comment by ellyliang** [comment]
网址：www.ellyliang.me

**Comment by xlsdg** [comment]
看到问题的现象了，方便提供前端源码来调试定位问题吗？或者把 node_modules/vue-duoshuo/src/DuoShuo.vue 里的 console.log 注释打开，然后观察打印信息，截个图看看。

**Comment by ellyliang** [comment]
hi~我把console.log的注释打开了，看到了2个报错，一个是说thread希望是字符串，但是我已经改成字符串了。还有一个是说设置ds-thread-key,但是其实已经设置了。

截图如下：

![image](https://cloud.githubusercontent.com/assets/4658035/23102235/a5f566fc-f6e0-11e6-9707-b5d0d096b8d9.png)

**Comment by ellyliang** [comment]
解决了，改了2个地方，一个是props里边的thread要给个default，不然老是提示错误，一个是this.init()要放到updated里边

**Comment by xlsdg** [comment]
现象看上去是你的vue用法不对造成的报错，thread是不可能一开始就在组件内部定义default值。

**Comment by ellyliang** [comment]
恩恩，第一个问题是我的赋值问题，我一开始要给个默认的值...但是第二个问题，this.init()放到upldated里边就不会存在返回列表又返回来评论不存在的问题

**Comment by xlsdg** [comment]
很好，知道原因了，我改一下，发布个版本，然后你更新再试试。

**Comment by ellyliang** [comment]
好的，谢谢大神🌹

**Comment by xlsdg** [comment]
今天又修复了一个跟之前很类似的BUG，可以更新之后试试是否还会出现之前的问题。
