### ISSUE TITLE
关于文章页面切换后没有更新评论的问题

### ISSUE THREAD

**Issue by leenty** [xlsdg/vue-duoshuo#2]
啊喽哈！我在github上找到了你的多说组件，但是在用的时候遇到了这个问题

情况是这样，我从demoA文章切换到demoB文章，传入`props`的参数也有变化，但是评论却没有变化
应用的大体结构是这个样子
```
/article/demoA                /article/demoB     
+------------------+           +-----------------+ 
| article          |           | article         | 
| +--------------+ |           | +-------------+ | 
| | demoA        | |  +----->  | | demoB       | | 
| |              | |           | |             | | 
| +--------------+ |           | +-------------+ | 
| duoshuo          |           | duoshuo         | 
+------------------+           +-----------------+ 
```
两层路由，多说在第一层，文章在第二次，改变第二层路由时会改变传入多说组件的`props`，但是评论去没有改变，所以过来求助

**Comment by xlsdg** [comment]
上次有修复过类似的问题，有仓库代码提供调试么？这样好定位问题

**Comment by leenty** [comment]
我今天电脑不在身边，明天9点后，我会把地址发出来，需要有vue的dev-tool调试的吧。麻烦啦

**Comment by leenty** [comment]
抱歉，晚了😅，[测试地址](http://vue2-dev.leenty.com/), [代码仓库](https://github.com/leenty/vue2/tree/dev)

**Comment by xlsdg** [comment]
非常感谢你的例子，已经定位到问题，一会儿修复发个版本。

**Comment by xlsdg** [comment]
修复问题之后，插件传的参数有所改变，详细看说明文档。

**Comment by leenty** [comment]
兄弟，你是不是有什么地方会造成死循环的？我切换路由的时候会cpu吃满卡死，去掉这个组件就没事了。

**Comment by xlsdg** [comment]
我本地重新克隆了你的仓库，切到dev分支，把vue-duoshuo的版本号改成1.0.6后npm i，然后npm run dev，测试了一下，没发现任何问题，你是怎么操作的？

**Comment by leenty** [comment]
咦，那是什么情况,参数我给了`domain`和`thread`，难道是没有其他参数的原因么，我现在确实是1.0.6
![image](https://cloud.githubusercontent.com/assets/13213680/24081200/d8e9a388-0ce9-11e7-8820-c08e7d30dd4d.png)

**Comment by xlsdg** [comment]
其他参数不给也没关系的，你照我说的步骤在一个新位置拉取仓库操作一遍试试。

**Comment by leenty** [comment]
咦！奇怪了0.0 我重新拉取了就可以用了什么鬼，ok，解决了，多谢😉
